#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create venv if it doesn't exist
if [[ ! -d "venv" ]]; then
    python3 -m venv venv
fi

# Install development requirements into venv
venv/bin/pip install --requirement requirements-dev.txt

# Setup git commit hooks
venv/bin/pre-commit install
